### ISSUE TITLE
If Airplane is turned on when the app starts it crashes when trying to get NTP

### ISSUE THREAD

**Issue by Svahnen** [Svahnen/Android-NTP-Demo#2]
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.svahnen.synchronizedclock, PID: 2942
    java.lang.NullPointerException: null buffer || null address
        at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:120)
        at java.net.DatagramSocket.send(DatagramSocket.java:721)
        at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:90)
        at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:113)
        at com.svahnen.synchronizedclock.ClockConfig.getCurrentNetworkTime(ClockConfig.java:84)
        at com.svahnen.synchronizedclock.ClockConfig$1.run(ClockConfig.java:45)

**Comment by Svahnen** [comment]
Fixed in 72e540cea67e3e0d3b6a0f501fb41117ea55a0e8
